### ISSUE TITLE
Automate version number bumping

### ISSUE THREAD

**Issue by alpipego** [alpipego/resizefly#16]
There are three places in which the version number needs to be bumped:

- readme.txt
- resizefly.php plugin header
- bootstrap.php plugin config

I always forget one of them; the process has to be automated.

**Comment by hofmannsven** [comment]
Maybe something like this: [`fumikito/wp-readme`](https://github.com/fumikito/wp-readme).

**Comment by alpipego** [comment]
Thanks for reminding me of this issue, @hofmannsven. I have a readme.txt to README.md grunt task running.
I've added automatic version bumping to the git-flow `post-flow-hotfix-start` and `post-flow-release-start` hooks:

```
sed -i "s/^\(.*Version:\s*\)\([0-9.]*\)/\1$VERSION/" $ROOTDIR/resizefly.php
sed -i "s/^\(.*\['config\.version'\]\s*=\s*\)\('[0-9.]*'\;\)/\1'$VERSION';/" $ROOTDIR/app/bootstrap.php
sed -i "s/^\(Stable tag:\s*\)\([0-9.]*\)/\1$VERSION/" $ROOTDIR/readme.txt
```

since no one besides is going to be releasing this plugin, I'll keep it here for reference but not add the hook to version control.
