### ISSUE TITLE
Media Library stop showing thumbnails

### ISSUE THREAD

**Issue by parthwp** [alpipego/resizefly#27]
Hello,

Once I deactivate the plugin it stops showing thumbnails in media library, also it is having conflict with Rank Math plugin, if I activate the rank math plugin it stops showing images in media library.

Can you please check it.

Looking forward to here from you soon

Thank You

**Comment by alpipego** [comment]
> Once I deactivate the plugin it stops showing thumbnails in media library

That's the expected behavior, cf. https://github.com/alpipego/resizefly#uninstalling

> also it is having conflict with Rank Math plugin

I'll take a look at this.

**Comment by parthwp** [comment]
Hello I am facing the thumbnail issue when I am activating Rank math plugin can you please look for it as well.

**Comment by parthwp** [comment]
Hello Resizefly team, I have the raised the ticket with Rank Math support team and they are ready to work with you guys to solve the issue. can you please help us solve it asap

**Comment by alpipego** [comment]
Sure man. I'm a solo developer on a free and open source software. I'll look into it as soon as I can.
