### ISSUE TITLE
Why Separate Images

### ISSUE THREAD

**Issue by hirenshah** [alpipego/resizefly#30]
This question is probably due to my lack of knowledge / understanding... from what I can tell, this plugin suppresses WordPress's creation of resized versions and serves its own copy of them from an alternative location. 

Is it not possible to place them exactly where WordPress would have placed them, for example:
`/wp-content/uploads/2020/03/`

And use the same naming convention etc.  Basically go through the same process flow that WordPress would do, but dynamically (if and when required).

This seems too obvious, so I guess I am missing something here and/or it isn't actually possible to do that.

**Comment by alpipego** [comment]
The idea behind it is to have a cache folder that you can delete without using valuable data. The process of going through all images and figuring out whether it is the original, a manually cropped version or one that we can easily recreate is very tedious and memory consuming. Especially on large media libraries.

For a very simple system, I agree with you and might think about building a plugin that does only that.

**Comment by hirenshah** [comment]
Surely you would know what the images are based on how they are named?  For example, I have:
`test-image.jpg`

WordPress creates resized versions with names like:
```
test-image-350x350.jpg
test-image-2048x1336.jpg
```

I've disabled all the random sizes so would know exactly what they are, and was thinking it would be better to just keep them like WordPress would usually do.

However, I hadn't thought about this as being like "caching" so it initially didn't make sense to me... it does now though :)

**Comment by alpipego** [comment]
What if someone uploads an image that already has a file ending like `-350x350.jpg`? Your approach is going to delete original images from users file system.

**Comment by hirenshah** [comment]
If you try and upload a file with the same name, WordPress appends a number at the end.  So, if I uploaded the same file as in my earlier example, it would get saved as:
`test-image-2.jpg`

It's resized versions would then be:
```
test-image-2-350x350.jpg
test-image-2-2048x1336.jpg
```

**Comment by alpipego** [comment]
If you upload `test-image-2048x1336.jpg` to your media library, WordPress will create `test-image-2048-1336-350x350.jpg` for the downsized media. So a simple regex on the image dimensions is not going to cut it.

**Comment by hirenshah** [comment]
Am I missing something obvious here? Surely this would be no different to how WordPress manages things?

In terms of the regex, this works:

You can use a simple regex like this:
`-\d+[Xx]\d+\.`

**Comment by alpipego** [comment]
That'll also catch the original from https://github.com/alpipego/resizefly/issues/30#issuecomment-595711255

**Comment by hirenshah** [comment]
![SmartSelect_20200306-130840_Chrome Beta](https://user-images.githubusercontent.com/418112/76086251-a3c71100-5fab-11ea-8c3d-438e91138488.jpg)

**Comment by alpipego** [comment]
https://regex101.com/r/BvlZjY/3

**Comment by hirenshah** [comment]
Apologies, I misunderstood what you meant by that. Easy solution to that is to sanitise filenames on upload, which is something I do currently with my uploads.

I currently make everything lowercase, reduce any consecutive fullstops, hyphens, underscores etc to just a single one and also append post names or uploading user's display name as the prefix.

In this case you just match on the same regex upon upload and remove that from the filename.

**Comment by alpipego** [comment]
> Easy solution to that is to sanitise filenames on upload

If you go back to your initial post on this ticket, you said

> And use the same naming convention

So, in my opinion, messing with filenames is worse than adding a caching folder to the image path; and there is an option to change the directory name.

Sanitizing is also a problem for already uploaded files and those that are being resized by the user in the WordPress media library. 

As I said, I'll consider adding your suggestion as an option instead of the caching folder, but I'd strongly advise against using it on "bigger" media libraries.
